spring.application.name=dynamic-rbac
spring.profiles.default=dev
server.port=${PORT:8080}
spring.sql.init.mode=never
spring.jpa.open-in-view=false
app.seed.enabled=${APP_SEED_ENABLED:true}
app.seed.admin.username=${SEED_ADMIN_USERNAME:admin}
app.seed.admin.password=${SEED_ADMIN_PASSWORD:admin123}
app.seed.user1.username=${SEED_USER1_USERNAME:user1}
app.seed.user1.password=${SEED_USER1_PASSWORD:user123}
app.seed.user2.username=${SEED_USER2_USERNAME:user2}
app.seed.user2.password=${SEED_USER2_PASSWORD:user123}
